const knowledgeIndex = {
  "html div tag": "chunk_0000.js",
  "html span tag": "chunk_0000.js",
  "html a tag": "chunk_0001.js",
  "html img tag": "chunk_0001.js",
  "html p tag": "chunk_0002.js",
  "html h1 tag": "chunk_0002.js",
  "html h2 tag": "chunk_0003.js",
  "html h3 tag": "chunk_0003.js",
  "html ul tag": "chunk_0004.js",
  "html li tag": "chunk_0004.js",
  "html ol tag": "chunk_0005.js",
  "html table tag": "chunk_0005.js",
  "html tr tag": "chunk_0006.js",
  "html td tag": "chunk_0006.js",
  "html th tag": "chunk_0007.js",
  "html form tag": "chunk_0007.js",
  "html input tag": "chunk_0008.js",
  "html button tag": "chunk_0008.js",
  "html script tag": "chunk_0009.js",
  "html style tag": "chunk_0009.js",
  "html link tag": "chunk_0010.js",
  "html meta tag": "chunk_0010.js",
  "html head tag": "chunk_0011.js",
  "html body tag": "chunk_0011.js",
  "html html tag": "chunk_0012.js",
  "html header tag": "chunk_0012.js",
  "html footer tag": "chunk_0013.js",
  "html nav tag": "chunk_0013.js",
  "html section tag": "chunk_0014.js",
  "html article tag": "chunk_0014.js",
  "html aside tag": "chunk_0015.js",
  "html main tag": "chunk_0015.js",
  "html figure tag": "chunk_0016.js",
  "html figcaption tag": "chunk_0016.js",
  "html audio tag": "chunk_0017.js",
  "html video tag": "chunk_0017.js",
  "html source tag": "chunk_0018.js",
  "html canvas tag": "chunk_0018.js",
  "html svg tag": "chunk_0019.js",
  "html iframe tag": "chunk_0019.js",
  "html embed tag": "chunk_0020.js",
  "html object tag": "chunk_0020.js",
  "html param tag": "chunk_0021.js",
  "html map tag": "chunk_0021.js",
  "html area tag": "chunk_0022.js",
  "html br tag": "chunk_0022.js",
  "html hr tag": "chunk_0023.js",
  "html b tag": "chunk_0023.js",
  "html strong tag": "chunk_0024.js",
  "html i tag": "chunk_0024.js",
  "html em tag": "chunk_0025.js",
  "html u tag": "chunk_0025.js",
  "html s tag": "chunk_0026.js",
  "html q tag": "chunk_0026.js",
  "html blockquote tag": "chunk_0027.js",
  "html code tag": "chunk_0027.js",
  "html pre tag": "chunk_0028.js",
  "html abbr tag": "chunk_0028.js",
  "html address tag": "chunk_0029.js",
  "html bdo tag": "chunk_0029.js",
  "html cite tag": "chunk_0030.js",
  "html del tag": "chunk_0030.js",
  "html dfn tag": "chunk_0031.js",
  "html ins tag": "chunk_0031.js",
  "html kbd tag": "chunk_0032.js",
  "html samp tag": "chunk_0032.js",
  "html var tag": "chunk_0033.js",
  "html sup tag": "chunk_0033.js",
  "html sub tag": "chunk_0034.js",
  "html small tag": "chunk_0034.js",
  "html mark tag": "chunk_0035.js",
  "html ruby tag": "chunk_0035.js",
  "html rt tag": "chunk_0036.js",
  "html rp tag": "chunk_0036.js",
  "html bdi tag": "chunk_0037.js",
  "html wbr tag": "chunk_0037.js",
  "html details tag": "chunk_0038.js",
  "html summary tag": "chunk_0038.js",
  "html dialog tag": "chunk_0039.js",
  "html menu tag": "chunk_0039.js",
  "html menuitem tag": "chunk_0040.js",
  "html fieldset tag": "chunk_0040.js",
  "html legend tag": "chunk_0041.js",
  "html label tag": "chunk_0041.js",
  "html select tag": "chunk_0042.js",
  "html datalist tag": "chunk_0042.js",
  "html optgroup tag": "chunk_0043.js",
  "html option tag": "chunk_0043.js",
  "html textarea tag": "chunk_0044.js",
  "html keygen tag": "chunk_0044.js",
  "html output tag": "chunk_0045.js",
  "html progress tag": "chunk_0045.js",
  "html meter tag": "chunk_0046.js",
  "html template tag": "chunk_0046.js",
  "html slot tag": "chunk_0047.js",
  "css color property": "chunk_0047.js",
  "css background-color property": "chunk_0048.js",
  "css font-size property": "chunk_0048.js",
  "css font-family property": "chunk_0049.js",
  "css margin property": "chunk_0049.js",
  "css padding property": "chunk_0050.js",
  "css border property": "chunk_0050.js",
  "css width property": "chunk_0051.js",
  "css height property": "chunk_0051.js",
  "css display property": "chunk_0052.js",
  "css position property": "chunk_0052.js",
  "css top property": "chunk_0053.js",
  "css right property": "chunk_0053.js",
  "css bottom property": "chunk_0054.js",
  "css left property": "chunk_0054.js",
  "css float property": "chunk_0055.js",
  "css clear property": "chunk_0055.js",
  "css z-index property": "chunk_0056.js",
  "css overflow property": "chunk_0056.js",
  "css text-align property": "chunk_0057.js",
  "css text-decoration property": "chunk_0057.js",
  "css text-transform property": "chunk_0058.js",
  "css line-height property": "chunk_0058.js",
  "css letter-spacing property": "chunk_0059.js",
  "css word-spacing property": "chunk_0059.js",
  "css white-space property": "chunk_0060.js",
  "css vertical-align property": "chunk_0060.js",
  "css list-style property": "chunk_0061.js",
  "css list-style-type property": "chunk_0061.js",
  "css list-style-position property": "chunk_0062.js",
  "css list-style-image property": "chunk_0062.js",
  "css border-collapse property": "chunk_0063.js",
  "css border-spacing property": "chunk_0063.js",
  "css caption-side property": "chunk_0064.js",
  "css empty-cells property": "chunk_0064.js",
  "css table-layout property": "chunk_0065.js",
  "css outline property": "chunk_0065.js",
  "css outline-width property": "chunk_0066.js",
  "css outline-style property": "chunk_0066.js",
  "css outline-color property": "chunk_0067.js",
  "css box-shadow property": "chunk_0067.js",
  "css opacity property": "chunk_0068.js",
  "css visibility property": "chunk_0068.js",
  "css cursor property": "chunk_0069.js",
  "css content property": "chunk_0069.js",
  "css quotes property": "chunk_0070.js",
  "css counter-reset property": "chunk_0070.js",
  "css counter-increment property": "chunk_0071.js",
  "css page-break-before property": "chunk_0071.js",
  "css page-break-after property": "chunk_0072.js",
  "css page-break-inside property": "chunk_0072.js",
  "css flex property": "chunk_0073.js",
  "css flex-direction property": "chunk_0073.js",
  "css flex-wrap property": "chunk_0074.js",
  "css flex-flow property": "chunk_0074.js",
  "css justify-content property": "chunk_0075.js",
  "css align-items property": "chunk_0075.js",
  "css align-content property": "chunk_0076.js",
  "css order property": "chunk_0076.js",
  "css flex-grow property": "chunk_0077.js",
  "css flex-shrink property": "chunk_0077.js",
  "css flex-basis property": "chunk_0078.js",
  "css align-self property": "chunk_0078.js",
  "css grid property": "chunk_0079.js",
  "css grid-template-columns property": "chunk_0079.js",
  "css grid-template-rows property": "chunk_0080.js",
  "css grid-template-areas property": "chunk_0080.js",
  "css grid-template property": "chunk_0081.js",
  "css grid-column-gap property": "chunk_0081.js",
  "css grid-row-gap property": "chunk_0082.js",
  "css grid-gap property": "chunk_0082.js",
  "css grid-auto-columns property": "chunk_0083.js",
  "css grid-auto-rows property": "chunk_0083.js",
  "css grid-auto-flow property": "chunk_0084.js",
  "css grid-column property": "chunk_0084.js",
  "css grid-row property": "chunk_0085.js",
  "css grid-area property": "chunk_0085.js",
  "css justify-items property": "chunk_0086.js",
  "css justify-self property": "chunk_0086.js",
  "css transform property": "chunk_0087.js",
  "css transform-origin property": "chunk_0087.js",
  "css transform-style property": "chunk_0088.js",
  "css perspective property": "chunk_0088.js",
  "css perspective-origin property": "chunk_0089.js",
  "css backface-visibility property": "chunk_0089.js",
  "css transition property": "chunk_0090.js",
  "css transition-property property": "chunk_0090.js",
  "css transition-duration property": "chunk_0091.js",
  "css transition-timing-function property": "chunk_0091.js",
  "css transition-delay property": "chunk_0092.js",
  "css animation property": "chunk_0092.js",
  "css animation-name property": "chunk_0093.js",
  "css animation-duration property": "chunk_0093.js",
  "css animation-timing-function property": "chunk_0094.js",
  "css animation-delay property": "chunk_0094.js",
  "css animation-iteration-count property": "chunk_0095.js",
  "css animation-direction property": "chunk_0095.js",
  "css animation-fill-mode property": "chunk_0096.js",
  "css animation-play-state property": "chunk_0096.js",
  "javascript console.log": "chunk_0097.js",
  "javascript document.getelementbyid": "chunk_0097.js",
  "javascript document.queryselector": "chunk_0098.js",
  "javascript document.queryselectorall": "chunk_0098.js",
  "javascript document.createelement": "chunk_0099.js",
  "javascript document.createtextnode": "chunk_0099.js",
  "javascript document.addeventlistener": "chunk_0100.js",
  "javascript document.removeeventlistener": "chunk_0100.js",
  "javascript window.settimeout": "chunk_0101.js",
  "javascript window.setinterval": "chunk_0101.js",
  "javascript window.cleartimeout": "chunk_0102.js",
  "javascript window.clearinterval": "chunk_0102.js",
  "javascript window.alert": "chunk_0103.js",
  "javascript window.confirm": "chunk_0103.js",
  "javascript window.prompt": "chunk_0104.js",
  "javascript window.open": "chunk_0104.js",
  "javascript window.close": "chunk_0105.js",
  "javascript window.scrollto": "chunk_0105.js",
  "javascript window.scrollby": "chunk_0106.js",
  "javascript window.getcomputedstyle": "chunk_0106.js",
  "javascript array.isarray": "chunk_0107.js",
  "javascript array.from": "chunk_0107.js",
  "javascript array.of": "chunk_0108.js",
  "javascript array.prototype.concat": "chunk_0108.js",
  "javascript array.prototype.copywithin": "chunk_0109.js",
  "javascript array.prototype.entries": "chunk_0109.js",
  "javascript array.prototype.every": "chunk_0110.js",
  "javascript array.prototype.fill": "chunk_0110.js",
  "javascript array.prototype.filter": "chunk_0111.js",
  "javascript array.prototype.find": "chunk_0111.js",
  "javascript array.prototype.findindex": "chunk_0112.js",
  "javascript array.prototype.foreach": "chunk_0112.js",
  "javascript array.prototype.includes": "chunk_0113.js",
  "javascript array.prototype.indexof": "chunk_0113.js",
  "javascript array.prototype.join": "chunk_0114.js",
  "javascript array.prototype.keys": "chunk_0114.js",
  "javascript array.prototype.lastindexof": "chunk_0115.js",
  "javascript array.prototype.map": "chunk_0115.js",
  "javascript array.prototype.pop": "chunk_0116.js",
  "javascript array.prototype.push": "chunk_0116.js",
  "javascript array.prototype.reduce": "chunk_0117.js",
  "javascript array.prototype.reduceright": "chunk_0117.js",
  "javascript array.prototype.reverse": "chunk_0118.js",
  "javascript array.prototype.shift": "chunk_0118.js",
  "javascript array.prototype.slice": "chunk_0119.js",
  "javascript array.prototype.some": "chunk_0119.js",
  "javascript array.prototype.sort": "chunk_0120.js",
  "javascript array.prototype.splice": "chunk_0120.js",
  "javascript array.prototype.tolocalestring": "chunk_0121.js",
  "javascript array.prototype.tostring": "chunk_0121.js",
  "javascript array.prototype.unshift": "chunk_0122.js",
  "javascript array.prototype.values": "chunk_0122.js",
  "javascript string.fromcharcode": "chunk_0123.js",
  "javascript string.fromcodepoint": "chunk_0123.js",
  "javascript string.raw": "chunk_0124.js",
  "javascript string.prototype.charat": "chunk_0124.js",
  "javascript string.prototype.charcodeat": "chunk_0125.js",
  "javascript string.prototype.codepointat": "chunk_0125.js",
  "javascript string.prototype.concat": "chunk_0126.js",
  "javascript string.prototype.endswith": "chunk_0126.js",
  "javascript string.prototype.includes": "chunk_0127.js",
  "javascript string.prototype.indexof": "chunk_0127.js",
  "javascript string.prototype.lastindexof": "chunk_0128.js",
  "javascript string.prototype.localecompare": "chunk_0128.js",
  "javascript string.prototype.match": "chunk_0129.js",
  "javascript string.prototype.normalize": "chunk_0129.js",
  "javascript string.prototype.padend": "chunk_0130.js",
  "javascript string.prototype.padstart": "chunk_0130.js",
  "javascript string.prototype.repeat": "chunk_0131.js",
  "javascript string.prototype.replace": "chunk_0131.js",
  "javascript string.prototype.search": "chunk_0132.js",
  "javascript string.prototype.slice": "chunk_0132.js",
  "javascript string.prototype.split": "chunk_0133.js",
  "javascript string.prototype.startswith": "chunk_0133.js",
  "javascript string.prototype.substring": "chunk_0134.js",
  "javascript string.prototype.tolocalelowercase": "chunk_0134.js",
  "javascript string.prototype.tolocaleuppercase": "chunk_0135.js",
  "javascript string.prototype.tolowercase": "chunk_0135.js",
  "javascript string.prototype.tostring": "chunk_0136.js",
  "javascript string.prototype.touppercase": "chunk_0136.js",
  "javascript string.prototype.trim": "chunk_0137.js",
  "javascript string.prototype.valueof": "chunk_0137.js",
  "javascript object.assign": "chunk_0138.js",
  "javascript object.create": "chunk_0138.js",
  "javascript object.defineproperties": "chunk_0139.js",
  "javascript object.defineproperty": "chunk_0139.js",
  "javascript object.entries": "chunk_0140.js",
  "javascript object.freeze": "chunk_0140.js",
  "javascript object.fromentries": "chunk_0141.js",
  "javascript object.getownpropertydescriptor": "chunk_0141.js",
  "javascript object.getownpropertydescriptors": "chunk_0142.js",
  "javascript object.getownpropertynames": "chunk_0142.js",
  "javascript object.getownpropertysymbols": "chunk_0143.js",
  "javascript object.getprototypeof": "chunk_0143.js",
  "javascript object.is": "chunk_0144.js",
  "javascript object.isextensible": "chunk_0144.js",
  "javascript object.isfrozen": "chunk_0145.js",
  "javascript object.issealed": "chunk_0145.js",
  "javascript object.keys": "chunk_0146.js",
  "javascript object.preventextensions": "chunk_0146.js",
  "javascript object.seal": "chunk_0147.js",
  "javascript object.setprototypeof": "chunk_0147.js",
  "javascript object.values": "chunk_0148.js",
  "javascript math.abs": "chunk_0148.js",
  "javascript math.acos": "chunk_0149.js",
  "javascript math.acosh": "chunk_0149.js",
  "javascript math.asin": "chunk_0150.js",
  "javascript math.asinh": "chunk_0150.js",
  "javascript math.atan": "chunk_0151.js",
  "javascript math.atan2": "chunk_0151.js",
  "javascript math.atanh": "chunk_0152.js",
  "javascript math.cbrt": "chunk_0152.js",
  "javascript math.ceil": "chunk_0153.js",
  "javascript math.clz32": "chunk_0153.js",
  "javascript math.cos": "chunk_0154.js",
  "javascript math.cosh": "chunk_0154.js",
  "javascript math.exp": "chunk_0155.js",
  "javascript math.expm1": "chunk_0155.js",
  "javascript math.floor": "chunk_0156.js",
  "javascript math.fround": "chunk_0156.js",
  "javascript math.hypot": "chunk_0157.js",
  "javascript math.imul": "chunk_0157.js",
  "javascript math.log": "chunk_0158.js",
  "javascript math.log10": "chunk_0158.js",
  "javascript math.log1p": "chunk_0159.js",
  "javascript math.log2": "chunk_0159.js",
  "javascript math.max": "chunk_0160.js",
  "javascript math.min": "chunk_0160.js",
  "javascript math.pow": "chunk_0161.js",
  "javascript math.random": "chunk_0161.js",
  "javascript math.round": "chunk_0162.js",
  "javascript math.sign": "chunk_0162.js",
  "javascript math.sin": "chunk_0163.js",
  "javascript math.sinh": "chunk_0163.js",
  "javascript math.sqrt": "chunk_0164.js",
  "javascript math.tan": "chunk_0164.js",
  "javascript math.tanh": "chunk_0165.js",
  "javascript math.trunc": "chunk_0165.js",
  "javascript json.parse": "chunk_0166.js",
  "javascript json.stringify": "chunk_0166.js",
  "javascript date.now": "chunk_0167.js",
  "javascript date.parse": "chunk_0167.js",
  "javascript date.utc": "chunk_0168.js",
  "html": "chunk_0168.js",
  "css": "chunk_0169.js",
  "javascript": "chunk_0169.js",
  "python": "chunk_0170.js",
  "java": "chunk_0170.js",
  "c++": "chunk_0171.js",
  "c#": "chunk_0171.js",
  "ruby": "chunk_0172.js",
  "php": "chunk_0172.js",
  "swift": "chunk_0173.js",
  "go": "chunk_0173.js",
  "rust": "chunk_0174.js",
  "typescript": "chunk_0174.js",
  "sql": "chunk_0175.js",
  "nosql": "chunk_0175.js",
  "react": "chunk_0176.js",
  "angular": "chunk_0176.js",
  "vue": "chunk_0177.js",
  "node.js": "chunk_0177.js",
  "express": "chunk_0178.js",
  "django": "chunk_0178.js",
  "flask": "chunk_0179.js",
  "spring": "chunk_0179.js",
  "laravel": "chunk_0180.js",
  "ruby on rails": "chunk_0180.js",
  "asp.net": "chunk_0181.js",
  "mysql": "chunk_0181.js",
  "postgresql": "chunk_0182.js",
  "mongodb": "chunk_0182.js",
  "redis": "chunk_0183.js",
  "elasticsearch": "chunk_0183.js",
  "docker": "chunk_0184.js",
  "kubernetes": "chunk_0184.js",
  "aws": "chunk_0185.js",
  "azure": "chunk_0185.js",
  "google cloud": "chunk_0186.js",
  "heroku": "chunk_0186.js",
  "netlify": "chunk_0187.js",
  "vercel": "chunk_0187.js",
  "git": "chunk_0188.js",
  "github": "chunk_0188.js",
  "gitlab": "chunk_0189.js",
  "bitbucket": "chunk_0189.js",
  "linux": "chunk_0190.js",
  "windows": "chunk_0190.js",
  "macos": "chunk_0191.js",
  "android": "chunk_0191.js",
  "ios": "chunk_0192.js",
  "vscode": "chunk_0192.js"
};
